theme: jekyll-theme-minimal

title: Yue Qiu
description: Postdoctoral Researcher, <br> Computer Vision Research Team, <br> Artificial Intelligence Research Center, <br>National Institute of Advanced Industrial Science and Technology (AIST) <br>Email: qiu.yue [at] aist.go.jp <br> [[Github]](https://github.com/qiuyue1993/)
logo: /assets/qiuyue_2018.jpg
