theme: jekyll-theme-minimal

title: Yue Qiu
description: Postdoctoral Researcher, Computer Vision Research Team, Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology (AIST)
logo: /assets/qiuyue_2018.jpg
